---
name: CI for PRs
on: push

jobs:
  ci-build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout src
        uses: actions/checkout@v2

      - name: Build Test Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ruby-test-image:latest

      - name: Check Installed Dependencies in Image
        uses: addnab/docker-run-action@v1
        with:
          image: ruby-test-image:latest
          shell: sh
          run: |
            make --version
            ruby --version
            bundle --version
