---
name: CI for PRs
on:
  pull_request:
    types: [synchronize]

jobs:
  ci-build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Branch/Tree
        uses: actions/checkout@v2

      - name: Merge Changes in main Into PR Branch
        run: git fetch origin && git merge origin/main

      - name: Build Test Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ruby-test-image:latest

      - name: Check Installed Dependencies in Image
        run: |
          docker run --rm \
          --entrypoint sh \
          -v $GITHUB_WORKSPACE:/workspace \
          -w /workspace \
          ruby-test-image:latest
            make --version && ruby --version && bundle --version
